//LOGIN
export const SET_REDIRECT_URL = 'SET_REDIRECT_URL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_PROFILE_USER = 'GET_PROFILE_USER';